<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>TRXBuilders.TR3</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);SYSLIB1045;CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\TRXInjection.Sdk.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TR2\TRXBuilders.TR2.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
