using System.Reflection;
using System.Text;

namespace TRXInjectionTool.Format;

// Generates the TRXI format documentation from the format DTOs
// under TRXInjectionTool.Format. Regenerate with:
//   TRXInjectionTool --write-format-docs <path>
public static class FormatDocs
{
    private static readonly Dictionary<Type, string> _scalarNames = new()
    {
        [typeof(byte)] = "u8",
        [typeof(sbyte)] = "s8",
        [typeof(short)] = "s16",
        [typeof(ushort)] = "u16",
        [typeof(int)] = "s32",
        [typeof(uint)] = "u32",
        [typeof(float)] = "f32",
        [typeof(double)] = "f64",
    };

    private static readonly Dictionary<Type, string> _primNames = new()
    {
        [typeof(FormatVertex)] = "vertex",
        [typeof(FormatUV)] = "uv",
        [typeof(FormatColour)] = "colour",
        [typeof(FormatRoomInfo)] = "roominfo",
        [typeof(FormatFixed32)] = "fixed32",
        [typeof(FormatObjRef)] = "objref",
        [typeof(FormatSymbolRef)] = "symbol",
    };

    public static string Generate()
    {
        var sb = new StringBuilder();
        WritePreamble(sb);
        WriteTests(sb);
        WriteChunks(sb);
        WriteUnions(sb);
        WritePrimitives(sb);
        WriteVersioningPolicy(sb);
        return sb.ToString();
    }

    public static void Write(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path)));
        File.WriteAllText(path, Generate());
    }

    private static IEnumerable<Type> FormatTypes()
        => typeof(Container).Assembly.GetTypes()
            .Where(t => t.Namespace == typeof(Container).Namespace);

    private static FieldInfo[] Fields(Type t)
        => [.. t.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .OrderBy(f => f.MetadataToken)];

    private static string TypeName(FieldInfo field)
    {
        var t = field.FieldType;
        if (t.IsArray)
        {
            var elem = TypeNameOf(t.GetElementType());
            if (field.GetCustomAttribute<FixedLengthAttribute>() is { } fixedLen)
            {
                return $"{elem}[{fixedLen.Count}]";
            }
            if (field.GetCustomAttribute<LengthPrefixAttribute>() is { } prefix)
            {
                return $"{_scalarNames[prefix.CountType]} count, {elem}[count]";
            }
            if (field.GetCustomAttribute<ImpliedLengthAttribute>() is { } implied)
            {
                return $"{elem}[] — {implied.Note}";
            }
            throw new InvalidDataException(
                $"{field.DeclaringType.Name}.{field.Name}: array without a length attribute");
        }
        return TypeNameOf(t);
    }

    private static string TypeNameOf(Type t)
    {
        if (_scalarNames.TryGetValue(t, out var scalar))
        {
            return scalar;
        }
        if (_primNames.TryGetValue(t, out var prim))
        {
            return prim;
        }
        if (t == typeof(string))
        {
            return "s32 length, u8[length] text";
        }
        return t.GetCustomAttribute<UnionAttribute>(inherit: false) != null ? $"union {t.Name}" : t.Name;
    }

    private static void WriteRecordTable(StringBuilder sb, Type t, bool withHeading = true)
    {
        if (withHeading)
        {
            sb.AppendLine($"#### {t.Name}");
            sb.AppendLine();
        }
        var doc = t.GetCustomAttribute<FormatRecordAttribute>()?.Doc;
        if (doc != null)
        {
            sb.AppendLine(doc);
            sb.AppendLine();
        }

        var fields = Fields(t);
        if (fields.Length == 0)
        {
            sb.AppendLine("*empty payload*");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Field | Type | Notes |");
        sb.AppendLine("|---|---|---|");
        foreach (var f in fields)
        {
            var note = f.GetCustomAttribute<DocAttribute>()?.Text ?? "";
            sb.AppendLine($"| {char.ToLowerInvariant(f.Name[0])}{f.Name[1..]} | `{TypeName(f)}` | {note} |");
        }
        sb.AppendLine();
    }

    private static void WritePreamble(StringBuilder sb)
    {
        sb.AppendLine($"""
            <!-- Generated by TRXInjectionTool --write-format-docs; do not edit by hand. -->

            # TRXI injection binary format

            This document describes TRXI, format major version {Container.FormatMajor} —
            the injection file format produced by TRXInjectionTool and consumed by TRX.
            It is generated from the format DTOs in `sdk/Format/`, which are the
            single source of truth for both the serializer and this document.

            Design goals, in order:

            1. **Game-independence.** Every record has exactly one layout regardless of
               the targeted game; the engine converts canonical records to its native
               per-game structures at load time.
            2. **Skippability.** Applicability tests, chunks and blocks are framed with
               type, version and byte size, so readers can skip anything they do not
               understand.
            3. **Name-first references.** Content with a name is referenced through the
               symbol table rather than a fixed slot.

            All integers are little-endian. There is no implicit padding or alignment;
            structures are packed exactly as written.

            ## Container

            ```
            u32  magic       '{Container.Magic}'
            u32  formatMajor {Container.FormatMajor}
            u32  fileType    see below
            u32  rawLength   payload size once inflated
            u32  zlibLength  deflated payload size
            u8[] payload     zlib (deflate) stream
            ```

            The loader rejects the file with a logged warning when the
            magic differs, `formatMajor` is greater than its own, or the payload fails
            to inflate to exactly `rawLength` bytes.

            The whole payload is a single deflate stream: the shipped corpus is small
            (hundreds of files, median a few hundred bytes), one inflate per file is
            microseconds, readers cache the inflated payload, and skipping an entire
            irrelevant file already happens before decompression, keyed on `fileType`.
            Per-chunk compression would compress worse and buy nothing.

            ### File types
            """);
        sb.AppendLine();
        sb.AppendLine("| Value | Name | Gated by |");
        sb.AppendLine("|---|---|---|");
        foreach (var (value, name, note) in Container.FileTypes)
        {
            sb.AppendLine($"| {value} | {name} | {note} |");
        }
        sb.AppendLine();
        sb.AppendLine("""
            ## Payload

            ```
            applicability tests
            u32  chunkCount
            chunk * chunkCount
            ```
            """);
        sb.AppendLine();
    }

    private static void WriteTests(StringBuilder sb)
    {
        sb.AppendLine("""
            ## Applicability tests

            ```
            u32  testCount
            test * testCount

            test:
              u32  type
              u32  version   layout version of this test type, starting at 1
              u32  size      byte size of data
              u8[] data
            ```

            A file applies to the loaded level only when **every** test it carries
            passes. An unknown test type or version is skipped by `size` and treated
            as **failed**:
            an unknown condition cannot be assumed to hold.
            """);
        sb.AppendLine();

        var tests = FormatTypes()
            .Select(t => (Type: t, Attr: t.GetCustomAttribute<ApplicabilityAttribute>()))
            .Where(x => x.Attr != null)
            .OrderBy(x => x.Attr.TestType);
        foreach (var (type, attr) in tests)
        {
            sb.AppendLine($"### Test {attr.TestType}: {attr.Name} (version {attr.Version})");
            sb.AppendLine();
            if (attr.Doc != null)
            {
                sb.AppendLine(attr.Doc);
                sb.AppendLine();
            }
            WriteRecordTable(sb, type, withHeading: false);
        }
    }

    private static void WriteChunks(StringBuilder sb)
    {
        sb.AppendLine("""
            ## Chunks and blocks

            ```
            chunk:
              u32  type
              u32  version     layout version of this chunk type, starting at 1
              u32  blockCount
              u32  dataLength  byte size of data
              u8[] data        blockCount consecutive blocks

            block:
              u32  type
              u32  elementCount number of records in data
              u32  dataLength   byte size of data
              u8[] data
            ```

            Unknown chunk or block types, and chunk versions newer than the loader
            understands, are skipped by their size with a warning. `dataLength` is
            required: after a chunk or block, the loader must be exactly that
            many bytes past its header. Empty chunks and blocks are omitted; readers
            must not require any particular chunk to exist.
            """);
        sb.AppendLine();

        var blockBindings = FormatTypes()
            .SelectMany(t => t.GetCustomAttributes<BlockAttribute>().Select(a => (Type: t, Attr: a)))
            .ToLookup(x => x.Attr.ChunkType);

        var documented = new HashSet<Type>();
        foreach (var (chunkType, chunkName, version) in Container.Chunks)
        {
            sb.AppendLine($"### Chunk {chunkType}: {chunkName} (version {version})");
            sb.AppendLine();
            sb.AppendLine("| Block | Name | Payload record | Notes |");
            sb.AppendLine("|---|---|---|---|");
            var blocks = blockBindings[chunkType].OrderBy(x => x.Attr.BlockType).ToList();
            foreach (var (type, attr) in blocks)
            {
                sb.AppendLine($"| {attr.BlockType} | {attr.Name} | {TypeNameOf(type)} | {attr.Doc ?? ""} |");
            }
            sb.AppendLine();
            foreach (var (type, _) in blocks)
            {
                if (documented.Add(type))
                {
                    WriteReferencedRecords(sb, type, documented);
                }
            }
        }
    }

    // Renders a record table and, depth-first, the tables of records it nests.
    private static void WriteReferencedRecords(StringBuilder sb, Type t, HashSet<Type> documented)
    {
        if (t.GetCustomAttribute<UnionAttribute>(inherit: false) != null)
        {
            return; // unions get their own section
        }
        WriteRecordTable(sb, t);
        foreach (var f in Fields(t))
        {
            var nested = f.FieldType.IsArray ? f.FieldType.GetElementType() : f.FieldType;
            if (nested.Namespace == typeof(Container).Namespace
                && !_primNames.ContainsKey(nested)
                && !nested.IsEnum
                && nested.GetCustomAttribute<UnionAttribute>(inherit: false) == null
                && documented.Add(nested))
            {
                WriteReferencedRecords(sb, nested, documented);
            }
        }
    }

    private static void WriteUnions(StringBuilder sb)
    {
        sb.AppendLine("""
            ## Unions

            A union writes its discriminator first, then the base's common fields,
            then the payload of the matching case.
            """);
        sb.AppendLine();

        var unions = FormatTypes()
            .Where(t => t.GetCustomAttribute<UnionAttribute>(inherit: false) != null)
            .OrderBy(t => t.Name);
        foreach (var union in unions)
        {
            var attr = union.GetCustomAttribute<UnionAttribute>(inherit: false);
            sb.AppendLine($"### {union.Name} (discriminator: `{_scalarNames[attr.DiscriminatorType]}`)");
            sb.AppendLine();
            if (attr.Doc != null)
            {
                sb.AppendLine(attr.Doc);
                sb.AppendLine();
            }
            var header = Fields(union);
            if (header.Length > 0)
            {
                sb.AppendLine("Common header (after the discriminator):");
                sb.AppendLine();
                WriteRecordTable(sb, union, withHeading: false);
            }

            var cases = FormatTypes()
                .Where(t => t.BaseType == union)
                .Select(t => (Type: t, Case: t.GetCustomAttribute<CaseAttribute>()))
                .OrderBy(x => x.Case.Discriminator);
            foreach (var (type, caseAttr) in cases)
            {
                sb.AppendLine($"#### Case {caseAttr.Discriminator}: {type.Name}");
                sb.AppendLine();
                WriteRecordTable(sb, type, withHeading: false);
            }
        }
    }

    private static void WritePrimitives(StringBuilder sb)
    {
        sb.AppendLine("## Primitives");
        sb.AppendLine();
        foreach (var (type, name) in _primNames)
        {
            sb.AppendLine($"#### {name}");
            sb.AppendLine();
            var doc = type.GetCustomAttribute<FormatRecordAttribute>()?.Doc;
            if (doc != null)
            {
                sb.AppendLine(doc);
                sb.AppendLine();
            }
            sb.AppendLine("| Field | Type | Notes |");
            sb.AppendLine("|---|---|---|");
            foreach (var f in Fields(type))
            {
                var note = f.GetCustomAttribute<DocAttribute>()?.Text ?? "";
                sb.AppendLine($"| {char.ToLowerInvariant(f.Name[0])}{f.Name[1..]} | `{TypeName(f)}` | {note} |");
            }
            sb.AppendLine();
        }
    }

    private static void WriteVersioningPolicy(StringBuilder sb)
    {
        sb.AppendLine("""
            ## Versioning policy

            - Adding a new chunk, block, or test type: no version change anywhere —
              old readers skip it.
            - Changing an existing record's layout: bump that chunk's (or test's)
              version; old readers skip the newer chunk and log a warning.
            - Changing the container or the framing rules: bump `formatMajor` — a
              breaking change requiring all files to be regenerated.

            The injection tool's plugin handshake is keyed on `formatMajor` only;
            chunk-version evolution never invalidates builder plugins.
            """);
    }
}
